version: '3.9'

services:
  db:
    image: postgres:15
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env.prod
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"

  web:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.prod
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    command: >
      bash -c "
      bundle exec rails db:migrate &&
      bundle exec rails assets:precompile &&
      bundle exec puma -C config/puma.rb
      "
    restart: always
