---
openapi: 3.0.1
info:
  title: API V1
  version: v1
  description: Documentación de la API V1
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
- bearerAuth: []
paths:
  "/api/v1/register":
    post:
      summary: Registro de un nuevo usuario
      tags:
      - Auth
      parameters: []
      responses:
        '201':
          description: usuario registrado correctamente
        '422':
          description: parámetros inválidos
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
                password_confirmation:
                  type: string
              required:
              - email
              - password
              - password_confirmation
  "/api/v1/login":
    post:
      summary: Login de un usuario
      tags:
      - Auth
      parameters: []
      responses:
        '200':
          description: login exitoso
        '401':
          description: credenciales inválidas
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
              required:
              - email
              - password
  "/api/v1/users":
    get:
      summary: Lista de usuarios
      tags:
      - Users
      security:
      - bearerAuth: []
      responses:
        '200':
          description: usuarios listados
        '401':
          description: no autorizado
  "/api/v1/users/{id}":
    parameters:
    - name: id
      in: path
      description: ID del usuario
      required: true
      schema:
        type: string
    get:
      summary: Obtener detalles de un usuario
      tags:
      - Users
      security:
      - bearerAuth: []
      responses:
        '200':
          description: usuario encontrado
        '404':
          description: usuario no encontrado
    put:
      summary: Actualizar un usuario
      tags:
      - Users
      security:
      - bearerAuth: []
      parameters: []
      responses:
        '200':
          description: usuario actualizado
        '422':
          description: parámetros inválidos
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
                password_confirmation:
                  type: string
              required:
              - email
    delete:
      summary: Eliminar un usuario
      tags:
      - Users
      security:
      - bearerAuth: []
      responses:
        '200':
          description: usuario eliminado
        '404':
          description: usuario no encontrado
servers:
- url: http://localhost:3000
  variables:
    defaultHost:
      default: localhost:3000
