default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: <%= ENV['DATABASE_HOST'] %>
  pool: 5

development:
  <<: *default
  database: <%= ENV['DATABASE_DB'] %>

test:
  <<: *default
  database: <%= ENV['DATABASE_DB_TEST'] %>

production:
  <<: *default
  database: <%= ENV['DATABASE_DB'] %>
